DELIMITER $$
DROP FUNCTION IF EXISTS hexToRgb;
CREATE FUNCTION hexToRgb(hex char(7))
RETURNS CHAR(35)
DETERMINISTIC
BEGIN
	DECLARE p1 int(2);
	DECLARE p2 int(2);
	DECLARE p3 int(2);

	IF (SELECT SUBSTRING(hex,1,1)) = '#' THEN
		SET hex = (SELECT SUBSTRING(hex,2,6));
	END IF;

	SET p1 = (SELECT CONV(SUBSTRING(UPPER(hex),1,2),16,10));
	SET p2 = (SELECT CONV(SUBSTRING(UPPER(hex),3,2),16,10));
	SET p3 = (SELECT CONV(SUBSTRING(UPPER(hex),5,2),16,10));

	RETURN (SELECT CONCAT(p1,',',p2,',',p3));
END $$;